[build]
  command = "git lfs fetch && git lfs checkout && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  GIT_LFS_ENABLED = "1"
  GIT_LFS_SKIP_SMUDGE = "0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
