[build]
  command = "git lfs install && git lfs pull && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  GIT_LFS_ENABLED = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
